tests fabricantes
vidacalura/BonziTech-TCC pull request #22
Opened 2023-10-26 21:52 UTC by unknowuser6969

verificar o codigo de test

2023-10-26 22:03 UTC, vidacalura requested changes

2023-10-26 22:03 UTC, vidacalura commented on fabricantes.test.js
> +const { buscarFabricantes } = require('./fabricantes');
Arquivo e função inexistentes. Remover linha

2023-10-26 22:03 UTC, vidacalura commented on fabricantes.test.js
> +    const fabricantes = await buscarFabricantes();
Função chamada e não utilizada

2023-10-26 22:03 UTC, vidacalura commented on fabricantes.test.js
> +    expect(Array.isArray(fabricantes)).toBe(true);
Fabricantes sempre é nulo devido à função buscarFabricantes() não estar implementada

2023-10-26 22:03 UTC, vidacalura commented on fabricantes.test.js
> +    expect(fabricantes.length).toBeGreaterThan(0);
Confuso. Não é claro porque há 2 expects ou qual o intuito deste.

2023-10-26 22:03 UTC, vidacalura commented on fabricantes.test.js
> +  test('Deve lidar com uma falha na requisição à API', async () => {
Teste não necessário de se adicionar à API

2023-10-26 22:03 UTC, vidacalura commented on fabricantes.test.js
> +describe('Teste para fabricantes.js', () =>{
Teste duplicado do teste já existente na linha 16

2023-10-27 00:00 UTC, geovaniorsoli commented
gente que tanto de codigo errado gente

2023-10-28 02:19 UTC, vidacalura commented
O código claramente não demonstra um bom entendimento do funcionamento da API, com criações/edições de usuário não respeitando os campos obrigatórios, função não implementadas e diversas partes do código simplesmente não funcionando. Por favor, teste seu próprio código antes de enviá-lo e tenha certeza que o mesmo funciona.

2023-10-28 02:48 UTC, closed without merging